### ISSUE TITLE
安装 chinese_L-12_H-768_A-1报错

### ISSUE THREAD

**Issue by Eshter** [percent4/multi-label-classification-4-event-type#1]
bert-serving-start -model_dir chinese_L-12_H-768_A-12 -num_worker=1 #-http_port 8001
安装这个报错

I:VENTILATOR:[__i:__i: 67]:freeze, optimize and export graph, could take a while...
E:GRAPHOPT:[gra:opt:154]:fail to optimize the graph!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/bert_serving/server/graph.py", line 42, in optimize_graph
    tf = import_tf(verbose=args.verbose)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/bert_serving/server/helper.py", line 186, in import_tf
    tf.logging.set_verbosity(tf.logging.DEBUG if verbose else tf.logging.ERROR)
AttributeError: module 'tensorflow' has no attribute 'logging'

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/bert-serving-start", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/bert_serving/server/cli/__init__.py", line 4, in main
    with BertServer(get_run_args()) as server:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/bert_serving/server/__init__.py", line 71, in __init__
    self.graph_path, self.bert_config = pool.apply(optimize_graph, (self.args,))
TypeError: 'NoneType' object is not iterable

**Comment by Anti-entropyyy** [comment]
必须得是绝对路径

**Comment by Anti-entropyyy** [comment]
我也报错了，蹲一个

**Comment by Anti-entropyyy** [comment]
ValueError: invalid literal for int() with base 10: 'NVIDIA-SMI has failed because you are not:

**Comment by dogrepairditch** [comment]
> 必须得是绝对路径

我绝对路径也是错的
